/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.gemnasium

import com.gemnasium.extension.GemnasiumGradlePluginExtension
import com.gemnasium.extension.GemnasiumGradlePluginExtension.Companion.PLUGIN_EXTENSION_NAME
import com.gemnasium.tasks.DumpDependenciesTask
import org.gradle.api.Project
import org.gradle.api.Plugin

open class GemnasiumGradlePlugin: Plugin<Project> {
    override fun apply(project: Project) {
        project.extensions.create(PLUGIN_EXTENSION_NAME, GemnasiumGradlePluginExtension::class.java, project)
        // Create the task. We use tasks.create rather than tasks.register to be compatible with Gradle 3
        project.tasks.create(DumpDependenciesTask.TASK_NAME, DumpDependenciesTask::class.java)
    }
}
