/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.gemnasium

import com.gemnasium.tasks.DumpDependenciesTask
import org.gradle.api.Project
import org.gradle.api.Plugin

open class GemnasiumGradlePlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'com.gemnasium.gradle-plugin'")
            }
        }
        project.tasks.register(DumpDependenciesTask.TASK_NAME, DumpDependenciesTask::class.java)
    }
}
